version: "3.2"

services:
  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./api/src:/usr/src/app/src
