version: "3.2"

services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./api/src:/usr/src/app/src

  auth:
    environment:
      - NODE_ENV=development
    volumes:
      - ./auth/src:/usr/src/app/src

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
