version: "3.2"

services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=mongodb://api_db:27017/api
      - NODE_ENV=production
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api:
